apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "service-2"
        dapr.io/app-port: "5001"
    spec:
      containers:
        - name: service-2
          image: solexb/service-2:0.0.7
          ports:
            - containerPort: 5001
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "yb-tserver-service.yugabyte.svc.cluster.local"
            - name: DB_PORT
              value: "5433"
            - name: DB_NAME
              value: "yugabyte"
            - name: DB_USER
              value: "yugabyte"
            - name: DB_PASSWORD
              value: "yugabyte"

---
# service-2-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-2
  namespace: dev-2  # Match your namespace
spec:
  selector:
    app: service-2  # Matches the labels in your service-2 Deployment
  ports:
    - protocol: TCP
      port: 5001    # Port exposed by the Service
      targetPort: 5001  # Port exposed by the Pod (matches containerPort)