apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-org>/<your-gitops-repo>.git
    targetRevision: main
    path: argocd-apps
    directory:
      recurse: false
      include: "{arc-controller,arc-runner-set}/application.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
