metricsServer:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
operator:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

# helm repo add kedacore https://kedacore.github.io/charts
# helm repo update
# helm install keda kedacore/keda --namespace keda --create-namespace -f ../../keda/values.yml 